### ISSUE TITLE
'Action' object has no attribute 'fcurves' error on Blender 5.0

### ISSUE THREAD

**Issue by OfficialWiel** [dtzxporter/cast#97]
CAST importer doesn't work on the new Blender 5.0 release when trying to apply animation to a model, giving error 'Action' object has no attribute 'fcurves'
